version: "3.1"

services:
    drupal:
        image: drupal-fpm-alpine
        volumes:
            - drupal_modules:/var/www/html/modules
            - drupal_profiles:/var/www/html/profiles
            - drupal_themes:/var/www/html/themes
            - drupal_sites:/var/www/html/sites
        ports:
            - 8080:80
    pgsql:
        image: postgres:11-alpine
        environment:
            - POSTGRES_DB=drupal
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
        volumes:
            - pgsql_data:/var/lib/postgresql/data

volumes:
    drupal_modules:
    drupal_profiles:
    drupal_themes:
    drupal_sites:
    pgsql_data: